site_name: FocusedMe
site_description: A minimalist Pomodoro timer that runs in your terminal
repo_url: https://github.com/scopeta/focusedme
repo_name: scopeta/focusedme

# Remove MkDocs config now that Sphinx docs are used
